name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - beta

permissions:
  contents: read # for checkout

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Run linting
        run: yarn lint

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            lib
            use-debouncy-pack.tgz

  release:
    needs: build-and-test
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.RELEASE_BOT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: npm credentials
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

      - name: yarn credentials
        run: yarn config set npmAuthToken $NPM_TOKEN

      - name: Whoami
        run: yarn npm whoami --publish

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            lib

      - name: Release
        run: yarn release
